### ISSUE TITLE
Add Photo in readme.md file

### ISSUE THREAD

**Issue by Vandit-dev** [krshkun/klink#1]
Hey Krish !!!
pls add some pic in your repo so, it is very helpful for many folks to visualize things.
thank you.

**Comment by krshkun** [comment]
Thanks you Vandit, actually rn we haven't yet built anything, so waiting 👍

**Comment by Vandit-dev** [comment]
ok cool :smile: @krshkun.
Your project is interesting :hugs:
looking forward to contributing :raised_hands: to it.
